# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#pool:
#  vmImage: ubuntu-latest
pool:
  name: Abdeen

#stages:
# - stage : Mystage
#   jobs :
#   - job :  MyJob
#     strategy :
#         maxParallel : 1
#         matrix:
#              JOB1:
#                  Version: 1.0
#                  AppName: foo
#     steps:
#      - script:
#          echo "($Version)"
#          echo "($AppName)"
#        displayName : "Echo Variables"

name: sampleWeb_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- main
#resources:
#  webhooks:
#  - webhook: MVAUK
#    connection: Incoming Webhook
#    type: Incoming Webhook
variables: 
- name: webhookURL
  value: Abdeen
  
jobs:
- job: ActivityonWindows
  steps:
    success:
      name: One with everything
    #  runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@master
        - name: Microsoft Teams Notification
          uses: skitionek/notify-microsoft-teams@master
          if: always()
          with:
            webhook_url: https://vodafone.webhook.office.com/webhookb2/57d56a25-1bd8-43de-a333-251ee152be67@68283f3b-8487-4c86-adb3-a5228f18b893/IncomingWebhook/40060548445f42488a707b744a5c5c3d/ae86f284-3d1d-442b-8cd6-28c89bd0544f
            needs: ${{ toJson(needs) }}
            job: ${{ toJson(job) }}
            steps: ${{ toJson(steps) }}
            dry_run: True

    if_failure:
      name: Only if failure
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@master
        - name: Microsoft Teams Notification
          uses: skitionek/notify-microsoft-teams@master
          if: failure()
          with:
            webhook_url: https://vodafone.webhook.office.com/webhookb2/57d56a25-1bd8-43de-a333-251ee152be67@68283f3b-8487-4c86-adb3-a5228f18b893/IncomingWebhook/40060548445f42488a707b744a5c5c3d/ae86f284-3d1d-442b-8cd6-28c89bd0544f

  

 #       success{
 #          office365ConnectorSend (
 #           status: "Pipeline Status",
 #           webhookUrl: "https://vodafone.webhook.office.com/webhookb2/57d56a25-1bd8-43de-a333-251ee152be67@68283f3b-8487-4c86-adb3-a5228f18b893/IncomingWebhook/40060548445f42488a707b744a5c5c3d/ae86f284-3d1d-442b-8cd6-28c89bd0544f",
 #           color: '00ff00',
 #           message: "Test Successful: ${JOB_NAME}"
 #           )}
 #        failure{
 #          office365ConnectorSend (
 #           status: "Pipeline Status",
 #           webhookUrl: "https://vodafone.webhook.office.com/webhookb2/57d56a25-1bd8-43de-a333-251ee152be67@68283f3b-8487-4c86-adb3-a5228f18b893/IncomingWebhook/40060548445f42488a707b744a5c5c3d/ae86f284-3d1d-442b-8cd6-28c89bd0544f",
 #           color: '00ff00',
 #           message: "Test fail: ${JOB_NAME}"
 #           )}


