# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#pool:
#  vmImage: ubuntu-latest
pool:
  name: Abdeen

#stages:
# - stage : Mystage
#   jobs :
#   - job :  MyJob
#     strategy :
#         maxParallel : 1
#         matrix:
#              JOB1:
#                  Version: 1.0
#                  AppName: foo
#     steps:
#      - script:
#          echo "($Version)"
#          echo "($AppName)"
#        displayName : "Echo Variables"

name: sampleWeb_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- main
jobs:
- job: ActivityonWindows
  steps:
   - task: PowerShell@2
     inputs:
       targetType: 'inline'
       script: |
         # Write your PowerShell commands here.
         
         Write-Host "Hello World"

