# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

stages:
 - stage : Mystage
   jobs :
   - job :  MyJob
     strategy :
         maxParallel: 3
         matrix:
              JOB1:
                  Version: 1.0
                  AppName: foo
              JOB2:
                  Version: 2.0
                  AppName: bar
              JOB3:
                  Version: 3.0
                  AppName: foobar
         steps:
           - script:
                  echo "($Version)"
                  echo "($AppName)"
             displayName : "Echo Variables"
